sonar.projectKey=esi-jsm-ticket-producerr
sonar.javascript.lcov.reportPaths=output-folder/coverage/lcov.info
sonar.sources=output-folder/src
sonar.coverage.exclusions=**/config.ts,**/test/*
sonar.cpd.exclusions=**/test/*